# Generated by Django 6.0.7 on 2026-07-17 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Узел", max_length=100)),
                ("color", models.CharField(default="#3498db", max_length=7)),
                ("x", models.FloatField(default=100)),
                ("y", models.FloatField(default=100)),
                (
                    "transform_type",
                    models.CharField(
                        choices=[
                            ("linear", "Линейный"),
                            ("quadratic", "Квадратичный"),
                            ("logarithmic", "Логарифмический"),
                            ("sinusoidal", "Синусоидальный"),
                            ("custom", "Пользовательский"),
                        ],
                        default="linear",
                        max_length=20,
                    ),
                ),
                (
                    "transform_formula",
                    models.TextField(
                        blank=True,
                        help_text="Формула для пользовательского типа (например, 2*x-4)",
                        null=True,
                    ),
                ),
                ("value", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=1.0)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="simulator.node",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="simulator.node",
                    ),
                ),
            ],
        ),
    ]
